name: Test Python Script

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install xvfb
        export DISPLAY=:99

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace 'x' with the desired Python version (e.g., 3.8)

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script with Xvfb
      run: xvfb-run python main.py  # Replace 'main.py' with the actual filename of your Python script
